
language: ruby
rvm:
  - 2.3.1
  - 2.3.3
  - 2.4.0
  - 2.5.1
  - 2.6.0
  - 2.7.1

os:
  - linux
  - dist: xenial
  - dist: bionic
  - osx

#before_install:
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew bundle; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then which dpkg-deb || 'dpkg-deb not found'; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then which lintian || echo 'lintian not found'; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then which python || brew install python; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then which easy_install || echo 'easy_install not found'; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then which virtualenv || pip install --user virtualenv ; fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then which virtualenv-tools || pip install --user virtualenv virtualenv-tools ; fi
#  - |
#    export PATH="/Users/travis/Library/Python/2.7/bin:${PATH}"
#    virtualenv ${HOME}/.venv
#script: source ${HOME}/.venv/bin/activate && PATH=${PATH}:${HOME}/.local/bin bundle exec rspec
addons:
  apt:
    packages:
      - bsdtar
      - rpm
      - lintian
      - python3-setuptools
      - python3-pip
      - squashfs-tools
      - perl
